# Generated by Django 5.1 on 2024-08-30 17:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Docente', max_length=100)),
                ('turno', models.CharField(default='Informe o turno, manha/tarde/noite', max_length=30)),
                ('cod_treinamento', models.IntegerField(default=0, help_text='Inserir o número do código')),
                ('situacao', models.CharField(choices=[('formacao', 'Formação'), ('reciclagem', 'Reciclagem'), ('complementacao', 'Complementação')], default='formacao', help_text='Formação, reciclagem ou complementação', max_length=50)),
                ('carga_horaria', models.TimeField(default=datetime.time(0, 0))),
                ('quantidade_alunos', models.IntegerField(default=0)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('cliente', models.CharField(default='Cliente não informado', max_length=200)),
                ('aula_pratica', models.CharField(blank=True, max_length=50, null=True)),
                ('dificuldades', models.TextField(blank=True, help_text='Descreva as dificuldades encontradas no treinamento')),
                ('treinamento_requisitos', models.TextField(blank=True, help_text='Equipamentos e/ou processos que necessitam ser implementados para que os funcionários tenham êxito em suas atividades')),
                ('observacoes', models.TextField(blank=True, help_text='Descreva qualquer observação ocorrida no treinamento, atrasos, colaboradores que não concluíram o treinamento, não realizaram aula prática, etc')),
                ('critica_elogio', models.TextField(blank=True, help_text='Deixe uma crítica / elogio para que possa haver melhoria contínua')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='imagens')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imagem.docente')),
            ],
        ),
    ]
